import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Tell the browser to never restore the scroll position on load */}
        <script
          dangerouslySetInnerHTML={{
            __html: `history.scrollRestoration = "manual"`,
          }}
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <noscript>
          <div style={styles.overlay}>
            <div style={styles.modal}>
              <h1 style={styles.title}>
                Se requiere JavaScript para que el sitio funcione
              </h1>
              <p style={styles.text}>
                JavaScript necesita estar habilitado para ver este sitio web.
                Por favor activalo en los ajustes de tu navegador
              </p>
            </div>
          </div>
        </noscript>
        {children}
      </body>
    </html>
  );
}

const styles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "#ffffff", // Background color (covers your broken site)
    zIndex: 99999, // Ensures it sits on top of everything
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  } as const,
  modal: {
    padding: "2rem",
    maxWidth: "500px",
  },
  title: {
    fontSize: "2rem",
    marginBottom: "1rem",
    color: "#333",
  },
  text: {
    fontSize: "1.1rem",
    color: "#666",
    lineHeight: "1.5",
  },
};
